name: Bug Report
description: Something isn't working as expected
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill in as much detail as you can.

  - type: input
    id: version
    attributes:
      label: Junction version
      description: Which `@junctionjs/*` package version(s)?
      placeholder: "@junctionjs/core@0.1.0"
    validations:
      required: true

  - type: dropdown
    id: runtime
    attributes:
      label: Runtime
      options:
        - Browser (Chrome)
        - Browser (Firefox)
        - Browser (Safari)
        - Node.js
        - Cloudflare Workers
        - Deno
        - Bun
        - Vercel Edge
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Code snippet, repo link, or steps to reproduce.
      render: typescript
    validations:
      required: true
