name: Feature Request
description: Suggest an improvement or new capability
labels: ["enhancement"]
body:
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What problem are you trying to solve? Describe the situation, not just the solution.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: How do you think this should work? Code examples are great.
      render: typescript

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?

  - type: dropdown
    id: scope
    attributes:
      label: Which package(s)?
      multiple: true
      options:
        - "@junctionjs/core"
        - "@junctionjs/client"
        - "@junctionjs/astro"
        - "@junctionjs/gateway"
        - "@junctionjs/debug"
        - "New package"
        - "Not sure"
